server:
  port: 7072
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jrtp26
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    rest:
      base-path: /api2
  boot:
   admin:
     client:
       url: http://localhost:1111/      
management:
  endpoints:
    web:
      exposure:
        include: '*'        
razorpay:
  key:
    id: rzp_test_3uOdeDij1shQB1 
    secret: FgyY2c4x2X5lalmnraDnw7g4       
